version: "3.8"
services:
  tensorboard:
    image: tensorboard
    build:
      context: ./
      dockerfile: tensorboard.Dockerfile
    ports:
      - ${TENSORBOARD_PORT}:${TENSORBOARD_PORT}
    volumes:
      - ${ROOT_DIR}:/jupyter
    command:
      [
        "tensorboard",
        "--logdir=${TENSORBOARD_DIR}",
        "--port=${TENSORBOARD_PORT}",
        "--bind_all"
      ]

  deeplearning-cpu-server:
    image: deeplearning-dev-cpu
    build:
      context: ./
      dockerfile: cpu.Dockerfile
    init: true
    env_file: ./.env
    ports:
      - ${JUPYTER_PORT}:${JUPYTER_PORT}
    volumes:
      - ${ROOT_DIR}:/${WORKSPACE_DIR}
      - ${ROOT_DIR}/notebooks:${JUPYTER_DIR}
    command:
      [
        "jupyter",
        "notebook",
        "--ip=*",
        "--port=${JUPYTER_PORT}",
        "--allow-root",
        "--notebook-dir=${JUPYTER_DIR}",
        '--NotebookApp.token=${JUPYTER_TOKEN}'
      ]
